// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68fYTHnM8dk9AeXM3j1hwzd9Gk5MGlqc',
    appId: '1:122748547317:web:73c815bb7c3bff6afa55bc',
    messagingSenderId: '122748547317',
    projectId: 'thesafeguard-222ea',
    authDomain: 'thesafeguard-222ea.firebaseapp.com',
    storageBucket: 'thesafeguard-222ea.appspot.com',
    measurementId: 'G-XN5FNQ7T7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVeFlT5I-BP84hU1mqDvtepIofX5_gTds',
    appId: '1:122748547317:android:016740b6c697ec53fa55bc',
    messagingSenderId: '122748547317',
    projectId: 'thesafeguard-222ea',
    storageBucket: 'thesafeguard-222ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmjCnDbzQvbPJK4P6ixyYnKP_pAArlKQ',
    appId: '1:122748547317:ios:feff3ea995513277fa55bc',
    messagingSenderId: '122748547317',
    projectId: 'thesafeguard-222ea',
    storageBucket: 'thesafeguard-222ea.appspot.com',
    iosClientId: '122748547317-9g5vahammkiu099240uirosnt4hfmq4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmjCnDbzQvbPJK4P6ixyYnKP_pAArlKQ',
    appId: '1:122748547317:ios:3c7bc160e434ee3efa55bc',
    messagingSenderId: '122748547317',
    projectId: 'thesafeguard-222ea',
    storageBucket: 'thesafeguard-222ea.appspot.com',
    iosClientId: '122748547317-44vohmkq1qtfgka0up2q0lfcr8pt7epe.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeGuard.RunnerTests',
  );
}
